In [7]:
import pandas as pd

In [10]:
df = pd.read_csv('ICE_ERO_PFD_DataFY2021_FY2025_Q1.xlsx - ICE Removals.csv')
df

,Arresting Agency,Criminality,Area of Responsibility (AOR),Country of Citizenship,Fiscal Year,Fiscal Quarter,Fiscal Month,Month-Year,Removals
0,CBP,Criminal Conviction,Atlanta,EL SALVADOR,2024,2,4,Jan 2024,10
1,CBP,Criminal Conviction,Atlanta,GUATEMALA,2021,1,1,Oct 2020,25
2,CBP,Criminal Conviction,Atlanta,GUATEMALA,2021,1,2,Nov 2020,18
3,CBP,Criminal Conviction,Atlanta,GUATEMALA,2023,1,2,Nov 2022,13
4,CBP,Criminal Conviction,Atlanta,GUATEMALA,2023,2,4,Jan 2023,10
...,...,...,...,...,...,...,...,...,...
7710,ICE,Other Immigration Violator,San Diego,MEXICO,2021,1,2,Nov 2020,15
7711,ICE,Other Immigration Violator,San Diego,MEXICO,2023,3,8,May 2023,10
7712,ICE,Other Immigration Violator,San Diego,MEXICO,2024,1,2,Nov 2023,10
7713,ICE,Other Immigration Violator,San Diego,MEXICO,2024,4,10,Jul 2024,12
7714,ICE,Other Immigration Violator,Seattle,MEXICO,2025,1,1,Oct 2024,17

In [ ]:
#How many revols in total?> 505.341

In [ ]:
#Removals column shows how many deportations happened at once.

In [116]:
total = df['Removals'].sum()
total

np.int64(505341)

In [ ]:
#check if there are null values > there arent.

In [36]:
df.isnull().sum()

Arresting Agency                0
Criminality                     0
Area of Responsibility (AOR)    0
Country of Citizenship          0
Fiscal Year                     0
Fiscal Quarter                  0
Fiscal Month                    0
Month-Year                      0
Removals                        0
Year                            0
Civil_Year                      0
Mounth                          0
dtype: int64

In [ ]:
#in the dataset, there is a column with the FISCAL year > and I don't want that.

In [ ]:
#I want the civil year, so I have to use the Month-Year column.

In [ ]:
# The 1º step is to check if it is already a in date type for Pandas.

In [13]:
df.dtypes

Arresting Agency                  str
Criminality                       str
Area of Responsibility (AOR)      str
Country of Citizenship            str
Fiscal Year                     int64
Fiscal Quarter                  int64
Fiscal Month                    int64
Month-Year                        str
Removals                        int64
dtype: object

In [ ]:
#It wasnt, so I had to transfer to that. If it shows datetime64[us], it means it worked.

In [15]:
df['Month-Year'] = pd.to_datetime(df['Month-Year'], format='%b %Y')
df['Month-Year']

0      2024-01-01
1      2020-10-01
2      2020-11-01
3      2022-11-01
4      2023-01-01
          ...
7710   2020-11-01
7711   2023-05-01
7712   2023-11-01
7713   2024-07-01
7714   2024-10-01
Name: Month-Year, Length: 7715, dtype: datetime64[us]

In [ ]:
#quero criar uma coluna com os anos civis, para saber qual foi o que teve mais removals.Uso a função do dt do pandas para achar anos.

In [34]:
df['Civil_Year'] = df['Month-Year'].dt.year
df['Civil_Year']

0       2024
1       2020
2       2020
3       2022
4       2023
        ...
7710    2020
7711    2023
7712    2023
7713    2024
7714    2024
Name: Civil_Year, Length: 7715, dtype: int32

In [ ]:
#somei só para checar se está certo e deu certo.

In [32]:
234269 + 154325 + 63730 + 36008 + 17009

505341

In [ ]:
#mas eu quero saber não o número de colunas que os anos aparecem, mas quantas remoções teve em cada ano.

In [49]:
year_real = df.groupby('Civil_Year')['Removals'].sum().sort_values(ascending=True).reset_index()
year_real

   Civil_Year  Removals
0        2020     17009
1        2021     36008
2        2022     63730
3        2023    154325
4        2024    234269

In [40]:
year_real.to_csv('year_real.csv', index=False)

In [ ]:
#qual a porcentagem de aumento?

In [52]:
inicio = year_real['Removals'].iloc[0]   # 2020
fim = year_real['Removals'].iloc[-1]    # 2024

In [60]:
aumento_total = ((fim - inicio) / inicio) * 100
aumento_total

In [67]:
(f"{aumento_total:.1f}%")

'1277.3%'

In [68]:
ano_antes = year_real['Removals'].iloc[-2]

In [69]:
aumento_final = ((fim - ano_antes) / ano_antes) * 100
aumento_final

np.float64(51.8023651385064)

In [63]:
vezes = fim / inicio
vezes

np.float64(13.773237697689458)

In [64]:
(f"{vezes:.1f}")

'13.8'

In [ ]:
#quantos países tem no gráfico? > 44 > achei buscando pelos .unique()

In [33]:
countries = df['Country of Citizenship'].unique()
countries

<StringArray>
[                    'EL SALVADOR',                       'GUATEMALA',
                        'HONDURAS',                          'MEXICO',
                        'COLOMBIA',                         'ECUADOR',
                       'NICARAGUA',                       'VENEZUELA',
              'DOMINICAN REPUBLIC',                          'BRAZIL',
             'REPUBLIC OF TÜRKIYE',                            'PERU',
      'CHINA, PEOPLES REPUBLIC OF',                            'CUBA',
                           'HAITI',                         'SENEGAL',
                      'UZBEKISTAN',                      'BANGLADESH',
                           'INDIA',                          'ANGOLA',
                         'TURKIYE',                         'BOLIVIA',
                        'CAMEROON',                           'CHILE',
                      'COSTA RICA',                         'GERMANY',
                           'ITALY',                      'MAURITANIA',
                         'MOROCCO',                           'SPAIN',
                  'UNITED KINGDOM',                     'AFGHANISTAN',
            'DEM REP OF THE CONGO',                         'SOMALIA',
                       'SRI LANKA',                         'ROMANIA',
                          'BELIZE',                         'GEORGIA',
                         'JAMAICA',                          'RUSSIA',
                           'EGYPT',                          'JORDAN',
 'MICRONESIA, FEDERATED STATES OF',                        'PAKISTAN']
Length: 44, dtype: str

In [107]:
countries_df = pd.DataFrame(countries, columns=['Country of Citizenship'])

In [108]:
countries_df.to_csv('countries_deportation.csv', index=False)

In [ ]:
#Quais os países que mais tiveram deportações?

In [5]:
nationality = df.groupby('Country of Citizenship')['Removals'].sum().sort_values(ascending=False)
nationality

Country of Citizenship
MEXICO                             224067
GUATEMALA                           96501
HONDURAS                            76235
EL SALVADOR                         27529
COLOMBIA                            25749
ECUADOR                             19390
PERU                                 7982
DOMINICAN REPUBLIC                   6888
NICARAGUA                            5726
BRAZIL                               4640
VENEZUELA                            2938
HAITI                                2342
INDIA                                1445
CHILE                                 875
REPUBLIC OF TÜRKIYE                   441
UZBEKISTAN                            323
SENEGAL                               284
TURKIYE                               261
CUBA                                  244
CHINA, PEOPLES REPUBLIC OF            237
BANGLADESH                            199
JAMAICA                               157
MAURITANIA                            134
SPAIN                                  83
AFGHANISTAN                            83
RUSSIA                                 76
BOLIVIA                                55
COSTA RICA                             49
CAMEROON                               47
ITALY                                  44
UNITED KINGDOM                         40
EGYPT                                  36
JORDAN                                 35
ANGOLA                                 32
SRI LANKA                              30
SOMALIA                                22
MICRONESIA, FEDERATED STATES OF        22
GEORGIA                                21
ROMANIA                                21
GERMANY                                14
PAKISTAN                               12
BELIZE                                 11
MOROCCO                                11
DEM REP OF THE CONGO                   10
Name: Removals, dtype: int64

In [7]:
nationality_df = nationality.reset_index()
nationality_df.columns = ['Country of Citizenship', 'Deportations']
nationality_df

             Country of Citizenship  Deportations
0                            MEXICO        224067
1                         GUATEMALA         96501
2                          HONDURAS         76235
3                       EL SALVADOR         27529
4                          COLOMBIA         25749
5                           ECUADOR         19390
6                              PERU          7982
7                DOMINICAN REPUBLIC          6888
8                         NICARAGUA          5726
9                            BRAZIL          4640
10                        VENEZUELA          2938
11                            HAITI          2342
12                            INDIA          1445
13                            CHILE           875
14              REPUBLIC OF TÜRKIYE           441
15                       UZBEKISTAN           323
16                          SENEGAL           284
17                          TURKIYE           261
18                             CUBA           244
19       CHINA, PEOPLES REPUBLIC OF           237
20                       BANGLADESH           199
21                          JAMAICA           157
22                       MAURITANIA           134
23                            SPAIN            83
24                      AFGHANISTAN            83
25                           RUSSIA            76
26                          BOLIVIA            55
27                       COSTA RICA            49
28                         CAMEROON            47
29                            ITALY            44
30                   UNITED KINGDOM            40
31                            EGYPT            36
32                           JORDAN            35
33                           ANGOLA            32
34                        SRI LANKA            30
35                          SOMALIA            22
36  MICRONESIA, FEDERATED STATES OF            22
37                          GEORGIA            21
38                          ROMANIA            21
39                          GERMANY            14
40                         PAKISTAN            12
41                           BELIZE            11
42                          MOROCCO            11
43             DEM REP OF THE CONGO            10

In [9]:
261 + 441

702

In [8]:
nationality_df.to_csv('nationality_deportation.csv', index=False)

In [74]:
top10 = nationality.sort_values(ascending=False).head(10)
top10

Country of Citizenship
MEXICO                224067
GUATEMALA              96501
HONDURAS               76235
EL SALVADOR            27529
COLOMBIA               25749
ECUADOR                19390
PERU                    7982
DOMINICAN REPUBLIC      6888
NICARAGUA               5726
BRAZIL                  4640
Name: Removals, dtype: int64

In [109]:
top10.to_csv('top10.csv')

In [76]:
import matplotlib.pyplot as plt

In [ ]:
#porcentagem

In [82]:
nationality_percent = nationality.value_counts(normalize=True) * 100
nationality_percent

Removals
83        4.545455
22        4.545455
21        4.545455
11        4.545455
224067    2.272727
96501     2.272727
76235     2.272727
27529     2.272727
25749     2.272727
19390     2.272727
7982      2.272727
6888      2.272727
5726      2.272727
4640      2.272727
2938      2.272727
2342      2.272727
1445      2.272727
875       2.272727
441       2.272727
323       2.272727
284       2.272727
261       2.272727
244       2.272727
237       2.272727
199       2.272727
157       2.272727
134       2.272727
76        2.272727
55        2.272727
49        2.272727
47        2.272727
44        2.272727
40        2.272727
36        2.272727
35        2.272727
32        2.272727
30        2.272727
14        2.272727
12        2.272727
10        2.272727
Name: proportion, dtype: float64

In [ ]:
#Which were the main criminality factors leading to deportation?

In [ ]:
#We can't just sort and count the criminality column, bc the number of deportations varies by rows.

In [89]:
df['Criminality'].unique()

<StringArray>
['Criminal Conviction', 'Pending Criminal Charges',
 'Other Immigration Violator']
Length: 3, dtype: str

In [ ]:
#os motivos são> 'Criminal Conviction', 'Pending Criminal Charges','Other Immigration Violator'

In [114]:
motive1 = df.groupby('Criminality')['Removals'].sum().sort_values(ascending=False)
motive1

Criminality
Other Immigration Violator    291720
Criminal Conviction           181915
Pending Criminal Charges       31706
Name: Removals, dtype: int64

In [118]:
motive1.to_csv('motive1.csv')

In [1]:
291720 + 181915 + 31706

505341

In [ ]:
#Whats the porcentage of the criminal convictions?

In [5]:
round((181915/505341)*100,3)

35.998

In [ ]:
# Who was the arrasting agency?

In [120]:
agency1 = df.groupby('Arresting Agency')['Removals'].sum().sort_values(ascending=False)
agency1

Arresting Agency
CBP    379962
ICE    125379
Name: Removals, dtype: int64

In [122]:
agency1.to_csv('agency1.csv')

In [121]:
379962 + 125379

505341